### ISSUE TITLE
Could not locate weather_app.py

### ISSUE THREAD

**Issue by charanravi-online** [Futura-Py/weather#12]
> To run this app, you will need Python 3 installed on your computer. Clone this repository and navigate to the directory containing the weather_app.py file.

When the repo was cloned, this is the file structutre I was greeted with:
![image](https://user-images.githubusercontent.com/84191978/236653525-b6ff6871-34d7-4d2f-aecf-cb5eddefba8d.png)

> Use the following command to install the required packages:
> pip install -r requirements.txt
The packages have been installed.

> Once the packages are installed, you can run the app using the following command:

> python3 weather_app.py
> or
> py3 weather_app.py

Could not locate the weather_app.py file.
I tried to locate it in the repo as well, but I can't seem to find it.
![image](https://user-images.githubusercontent.com/84191978/236653588-296d2571-3291-4969-8378-e959eb958c76.png)

The readme isn't udpated to the changes, perhaps?

Please do let me know if I'm looking in the wrong place/where I can look for.

**Comment by im-coder-lg** [comment]
I think we mean `main.py`. I don't remember seeing `weather*.py` here, since we follow some Python neatness rules. Try running the `main.py` file.

**Comment by im-coder-lg** [comment]
We'll resolve that soon :)

**Comment by Moosems** [comment]
I'll make a commit to fix this.
