### ISSUE TITLE
Dynamic Window Scaling

### ISSUE THREAD

**Issue by im-coder-lg** [Futura-Py/weather#15]
In progress - coded by @Moosems.

@Moosems Can you get the PR by this weekend? We could merge it by Sunday(I can since I have free time). Of course, if it is fine with you. I just want to know your vision of the dynamic scaling feature. Mine is like incremental values to the row data, so after searching, when the result is received, the values are configured and the window automatically makes space for the data. Can you explain your idea clearly so that I can understand it?

**Comment by Moosems** [comment]
I already started I just havent had a ton of time to work on it ;).

**Comment by im-coder-lg** [comment]
I added a branch that has a simple edition of the dynamic scaling feature. I added one commit(verified btw, yay!), but you can edit the file there. Just replace the file if you want :)

Branch: https://github.com/Futura-Py/weather/tree/dynamic-scaling

**Comment by im-coder-lg** [comment]
It is simple, so you can refactor it all you want. I'll help when needed.

**Comment by Moosems** [comment]
See my PR ;). I don't know why this is necessary though, the size of the labels will never be more than the original size, plus it is often frowned upon to change the app's size without the user asking for it :).

**Comment by Moosems** [comment]
The vertical scaling is not a great idea imo because I like having a predefined space for it :).

**Comment by im-coder-lg** [comment]
I guess for now, we will have dynamic scaling, and after adding Sun Valley and doing an overhaul, we can add icons, and settings, and anything else we need to add, and then remove dynamic scaling and make the window into a big, fixed size that dislays blank areas for the weather data, kind of like Gnome's stock weather app. What do you think?

**Comment by Moosems** [comment]
I'll make the settings drop downs in my PR to change the color mode and for the temperature units.

**Comment by Moosems** [comment]
I can implement the vertical scaling pretty easily in a possibly better way than you did but I also do enjoy apps that don't change size unless I myself resize it.

**Comment by not-nef** [comment]
i have already put a lot of work into the settings window for notes, maybe we could use the same one and just change the settings?

**Comment by sumeshir26** [comment]
> i have already put a lot of work into the settings window for notes, maybe we could use the same one and just change the settings?

That is a good idea. I can work on this.

**Comment by im-coder-lg** [comment]
The legendary @not-nef returns!

Yeah, we shall see how it works. I am thinking of a sidebar menu, what about you guys?

**Comment by Moosems** [comment]
> i have already put a lot of work into the settings window for notes, maybe we could use the same one and just change the settings?

I think we should just use a dropdown. Not necessary for a whole window.

**Comment by Moosems** [comment]
Let me show it in my PR ;).
