### ISSUE TITLE
Settings Window

### ISSUE THREAD

**Issue by im-coder-lg** [Futura-Py/weather#17]
The title.

Joking, here is my idea btw:

![Proposed Idea](https://github.com/Futura-Py/weather/assets/76845820/8cffe784-f975-4628-9bd7-72605bce54bd)

Continued from #16 

Please use this issue for your ideas. I might not be able to add a PR on this, so @Moosems @sumeshir26 I would need your help on this.

**Comment by not-nef** [comment]
hello i am also a programmer and i am pretty fit with ui

**Comment by not-nef** [comment]
although i dont quite get your drawing

**Comment by Moosems** [comment]
> hello i am also a programmer

I would hope so.

**Comment by Moosems** [comment]
> Joking, here is my idea btw:

Works good for me. I might work on a PR for this on Saturday.

**Comment by im-coder-lg** [comment]
> although i dont quite get your drawing

It's a design. You know that Sun Valley and Tkinger also allows tabbed windows, right? We can add anything else we need to add witht this feature. @Moosems can we try adding the About page in the settings tab itself? Might be easier. We ca also add the update mechanism like in https://GitHub.com/Futura-Py/TimerX

**Comment by not-nef** [comment]
ok do you want me to do anything for this project?

**Comment by im-coder-lg** [comment]
Hmm... @Moosems can you initiaise the PR? Me, @sumeshir26 and @not-nef will work on it together. We would have to refactor it repeatedly, trust me. I will add a list of things that we can implement and add some things myself. @sumeshir26 can you add the About page to the Settings tab? And @not-nef we need to add a simple update system like on TimerX, so can you do that? @Moosems I need your help to perfect this. I have a more elaborate vision, and will add it here soon.

**Comment by not-nef** [comment]
yeah i can start work on the updating system tomorrow

**Comment by Moosems** [comment]
The updates can't modify the bundle contents. So you can't just change the file.

**Comment by im-coder-lg** [comment]
![image](https://github.com/Futura-Py/weather/assets/76845820/1e6fb584-f8c2-4371-ab7f-645444171e21)
<a target="_blank" href="https://icons8.com/icon/cHO6jgTabrg7/settings">Settings</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a> btw

<details>
<summary>SVG for closer inspection</summary>

![Untitled-2023-08-24-2050](https://github.com/Futura-Py/weather/assets/76845820/3b2f89ae-12df-423f-a767-179bff0a23ba)

</details>

**Comment by not-nef** [comment]
i could do that since i have done pretty much exactly this for notes.

**Comment by im-coder-lg** [comment]
WE THOUGHT THE SAME THING?! Wow, talk about a freakin' coincidence!

**Comment by not-nef** [comment]
check it out github.com/futura-py/notes

**Comment by not-nef** [comment]
i habe put a lot of effort into it :)

**Comment by im-coder-lg** [comment]
Let @Moosems start. He really knows the code here, since he coded 99% of it. Then you add your changes, I will add mine, and @sumeshir26 can add a good About page with the icon. Yeah, we kind of got an icon. It was commented at #16, and I like it. We also need to add credits/links to icons if we did use them, like the settings one from Icons8.

**Comment by im-coder-lg** [comment]
Okay, gotta go!
![the-flash-salute](https://github.com/Futura-Py/weather/assets/76845820/5580acb3-36d5-48ab-aa72-36212a6595f8)

**Comment by not-nef** [comment]
yeah ok then i dont need to do anything since i dont really have any ideas. im not a very creative person

**Comment by Moosems** [comment]
> 

Remember, there are only two settings....

**Comment by sumeshir26** [comment]
> > Let @Moosems start. He really knows the code here, since he coded 99% of it. Then you add your changes, I will add mine, and @sumeshir26 can add a good About page with the icon. Yeah, we kind of got an icon. It was commented at #16, and I like it. We also need to add credits/links to icons if we did use them, like the settings one from Icons8.
> 
> Send me the icon so I can integrate it into the builds please!

https://user-images.githubusercontent.com/68823982/259160710-118fae2e-d570-431d-873a-6d59b3ff3e2d.png

**Comment by sumeshir26** [comment]
> once this project is finished i bet there will be a lot more

i hope so too - but in India this is my Boards(like a important exam) year so i will have very little time for coding very soon

**Comment by Moosems** [comment]
> once this project is finished i bet there will be a lot more

For? Units and color mode seems to be the only thing that really matters here. This project already got bloated by adding the sv_ttk feature.

**Comment by sumeshir26** [comment]
> > 
> 
> Remember, there are only two settings....

Yes, a full blown settings window will be kind of overkill here. But i guess it dosent hurt to get the framework in place so we can add more settings if and when we need to.

**Comment by im-coder-lg** [comment]
> > once this project is finished i bet there will be a lot more
> 
> i hope so too - but in India this is my Boards(like a important exam) year so i will have very little time for coding very soon

You said it. Same here. And I got competition at school.

> Remember, there are only two settings....

Hmm...

- API Key customisation for users
- Dark/Light/System mode(to each their own)
- Units(Imperial/Metric)

Anything else? I believe that is it _for now_.

> Yes, a full blown settings window will be kind of overkill here. But i guess it dosent hurt to get the framework in place so we can add more settings if and when we need to.

Well, setting up a layout always helps.

> For? Units and color mode seems to be the only thing that really matters here. This project already got bloated by adding the sv_ttk feature.

Perhaps we might have to use the multiple scripts method if it gets more bloated in the process. Honestly, it depends. But if it was like a multiple filesystem, maybe it is easy to manage, right?

**Comment by Moosems** [comment]
I like the design. I have recommended using a web scraper in the past instead of an API, thoughts?

**Comment by Moosems** [comment]
I can handle this next PR on my own, just want to iron out the details first.

**Comment by im-coder-lg** [comment]
> I like the design. I have recommended using a web scraper in the past instead of an API, thoughts?

How does that work?

> I can handle this next PR on my own, just want to iron out the details first.

We want to help though! I will try adding the API setting, and if I find anything else to add, I will add that. @sumeshir26 can integrate the app icon to the code, before we add it to packaging. @not-nef will add a similar update system like on TimerX. And you can refactor it to make it look better. Plus, I want to add some more things to the About page.

**Comment by not-nef** [comment]
> > I like the design. I have recommended using a web scraper in the past instead of an API, thoughts?
> 
> How does that work?

i think he just wants to do the `requests.get()` on a weather site

**Comment by sumeshir26** [comment]
> We want to help though! I will try adding the API setting, and if I find anything else to add, I will add that. @sumeshir26 can integrate the app icon to the code, before we add it to packaging. @not-nef will add a similar update system like on TimerX. And you can refactor it to make it look better. Plus, I want to add some more things to the About page.

Will take care of it in the next 3-4 hours.

**Comment by Moosems** [comment]
> i think he just wants to do the `requests.get()` on a weather site

Request the data from the website and then parse the data.

**Comment by sumeshir26** [comment]
@im-coder-lg Done with the icon.
@not-nef Any updates on update system?

**Comment by sumeshir26** [comment]
What does everyone think about separating the UI code and the weather API code into different files?

**Comment by im-coder-lg** [comment]
Better file management?

**Comment by Moosems** [comment]
> What does everyone think about separating the UI code and the weather API code into different files?

The API code is so simple it doesn't need its own file. This is a small project and doesn't need more than one file.

**Comment by not-nef** [comment]
> @im-coder-lg Done with the icon.
> 
> @not-nef Any updates on update system?

my gf was over today im afraid i can only work on it tomorrow. will do my best.

**Comment by im-coder-lg** [comment]
Okay, it's been a long time, so sorry to blast everyone's notification box. But something like this is on #21, but it's still in the WIP stage.
